In [1]:
import numpy as np

In [2]:
archivo_datos = 'slump_test.dat'

In [3]:
datos = np.loadtxt(archivo_datos, delimiter=',')

x = datos[:, 1:8]
y = datos[:, 8:12]

In [4]:
q,_ = np.shape(x)
_,m = np.shape(y)

In [5]:
A = np.c_[x,np.ones((q,1))]

In [6]:
# Optimizacion
ATA = A.T @ A
b = A.T @ y
theta = np.linalg.pinv(ATA) @ b

In [7]:
# Evalua la hipotesis
yh = A @ theta

In [8]:
# Evalua metricas
e = y-yh
ev = e.flatten(order = 'F')
# suma de los cuadrados de los errores
SSE = ev.T @ ev
# error cuadrado medio
MSE = SSE/(q*m)
RMSE = np.math.sqrt(MSE)

In [9]:
# Coeficiente de determinación (𝑅2)
# media
yb = np.mean(y)
e = y-yb
ev = e.flatten(order = 'F')
# suma de los cuadrados totales
SST = ev.T @ ev
# coeficiente de la determinacion
R2 = 1-SSE/SST

In [10]:
print("SSE   = ",SSE)
print("MSE   = ",MSE)
print("RMSE  = ",RMSE)
print("R2    = ",R2)
print("\nTHETA = ",theta)

SSE   =  21603.309012079484
MSE   =  69.91362139831548
RMSE  =  8.361436563074284
R2    =  0.777740199026264

THETA =  [[ 1.02157275e-02  5.36430924e-02  6.14132236e-02]
 [-1.29659581e-02 -5.69040345e-03 -2.97075235e-02]
 [ 6.17558878e-03  6.11509526e-02  5.05261143e-02]
 [ 2.58982296e-01  7.31798708e-01 -2.32695048e-01]
 [-1.83954019e-01  2.98328553e-01  1.03149914e-01]
 [ 2.97369173e-02  7.36601674e-02 -5.56216339e-02]
 [ 3.85840044e-02  9.40170896e-02 -3.90828685e-02]
 [-8.85250367e+01 -2.52874673e+02  1.39781500e+02]]
